# Generated by Django 5.0.4 on 2024-06-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bracelet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unnamed', max_length=100)),
                ('title_image', models.ImageField(blank=True, default=None, null=True, upload_to='static/media/jews')),
                ('copyright', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Браслет',
                'verbose_name_plural': 'Браслети',
            },
        ),
        migrations.CreateModel(
            name='Chainlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unnamed', max_length=100)),
                ('title_image', models.ImageField(blank=True, default=None, null=True, upload_to='static/media/jews')),
                ('copyright', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Ланцюжок',
                'verbose_name_plural': 'Ланцюжки',
            },
        ),
        migrations.CreateModel(
            name='CircletRing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unnamed', max_length=100)),
                ('title_image', models.ImageField(blank=True, default=None, null=True, upload_to='static/media/jews')),
                ('copyright', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Каблучка',
                'verbose_name_plural': 'Каблучки',
            },
        ),
        migrations.CreateModel(
            name='Earrings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unnamed', max_length=100)),
                ('title_image', models.ImageField(blank=True, default=None, null=True, upload_to='static/media/jews')),
                ('copyright', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Сережки',
                'verbose_name_plural': 'Сережки',
            },
        ),
        migrations.CreateModel(
            name='Kaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unnamed', max_length=100)),
                ('title_image', models.ImageField(blank=True, default=None, null=True, upload_to='static/media/jews')),
                ('copyright', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Каф',
                'verbose_name_plural': 'Кафи',
            },
        ),
        migrations.CreateModel(
            name='Necklace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unnamed', max_length=100)),
                ('title_image', models.ImageField(blank=True, default=None, null=True, upload_to='static/media/jews')),
                ('copyright', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Кольє',
                'verbose_name_plural': 'Кольє',
            },
        ),
        migrations.CreateModel(
            name='Pendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unnamed', max_length=100)),
                ('title_image', models.ImageField(blank=True, default=None, null=True, upload_to='static/media/jews')),
                ('copyright', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Підвіска',
                'verbose_name_plural': 'Підвіски',
            },
        ),
        migrations.CreateModel(
            name='SealRing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unnamed', max_length=100)),
                ('title_image', models.ImageField(blank=True, default=None, null=True, upload_to='static/media/jews')),
                ('copyright', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Печатка',
                'verbose_name_plural': 'Печатки',
            },
        ),
        migrations.CreateModel(
            name='WeddingRing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unnamed', max_length=100)),
                ('title_image', models.ImageField(blank=True, default=None, null=True, upload_to='static/media/jews')),
                ('copyright', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Обручка',
                'verbose_name_plural': 'Обручки',
            },
        ),
    ]
