# Generated by Django 5.0.4 on 2024-06-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracelet',
            name='title_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='webjew/static/media/jews'),
        ),
        migrations.AlterField(
            model_name='chainlet',
            name='title_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='webjew/static/media/jews'),
        ),
        migrations.AlterField(
            model_name='circletring',
            name='title_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='webjew/static/media/jews'),
        ),
        migrations.AlterField(
            model_name='earrings',
            name='title_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='webjew/static/media/jews'),
        ),
        migrations.AlterField(
            model_name='kaf',
            name='title_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='webjew/static/media/jews'),
        ),
        migrations.AlterField(
            model_name='necklace',
            name='title_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='webjew/static/media/jews'),
        ),
        migrations.AlterField(
            model_name='pendant',
            name='title_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='webjew/static/media/jews'),
        ),
        migrations.AlterField(
            model_name='sealring',
            name='title_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='webjew/static/media/jews'),
        ),
        migrations.AlterField(
            model_name='weddingring',
            name='title_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='webjew/static/media/jews'),
        ),
    ]
