# Generated by Django 5.0.4 on 2024-06-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjew', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='text',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
