# Generated by Django 5.0.4 on 2024-06-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webjew', '0005_feedback_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chainlet',
            options={'ordering': ['-id'], 'verbose_name': 'Ланцюжок', 'verbose_name_plural': 'Ланцюжки'},
        ),
        migrations.AlterModelOptions(
            name='kaf',
            options={'ordering': ['-id'], 'verbose_name': 'Каф', 'verbose_name_plural': 'Кафи'},
        ),
    ]
