# Generated by Django 5.0.4 on 2024-06-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjew', '0006_alter_chainlet_options_alter_kaf_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('page_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Консультація',
                'verbose_name_plural': 'Консультації',
            },
        ),
    ]
