# Generated by Django 5.0.4 on 2024-06-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjew', '0007_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracelet',
            name='model3d',
            field=models.FileField(blank=True, default=None, null=True, upload_to='webjew/static/media/3d'),
        ),
        migrations.AddField(
            model_name='chainlet',
            name='model3d',
            field=models.FileField(blank=True, default=None, null=True, upload_to='webjew/static/media/3d'),
        ),
        migrations.AddField(
            model_name='circletring',
            name='model3d',
            field=models.FileField(blank=True, default=None, null=True, upload_to='webjew/static/media/3d'),
        ),
        migrations.AddField(
            model_name='earrings',
            name='model3d',
            field=models.FileField(blank=True, default=None, null=True, upload_to='webjew/static/media/3d'),
        ),
        migrations.AddField(
            model_name='kaf',
            name='model3d',
            field=models.FileField(blank=True, default=None, null=True, upload_to='webjew/static/media/3d'),
        ),
        migrations.AddField(
            model_name='necklace',
            name='model3d',
            field=models.FileField(blank=True, default=None, null=True, upload_to='webjew/static/media/3d'),
        ),
        migrations.AddField(
            model_name='pendant',
            name='model3d',
            field=models.FileField(blank=True, default=None, null=True, upload_to='webjew/static/media/3d'),
        ),
        migrations.AddField(
            model_name='sealring',
            name='model3d',
            field=models.FileField(blank=True, default=None, null=True, upload_to='webjew/static/media/3d'),
        ),
        migrations.AddField(
            model_name='weddingring',
            name='model3d',
            field=models.FileField(blank=True, default=None, null=True, upload_to='webjew/static/media/3d'),
        ),
    ]
